version: '3.8'

networks:
  dev:
    driver: bridge
services:
  authentication_service:
    container_name: auth-service
    image: auth
    build:
      context: .  
      dockerfile: Services/Authentication/Authentication.API/Dockerfile
    ports:
      - "5011:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=User ID =postgres;Password=postgres;Server=dockerPostgres;Port=5432;Database=AuthDb;Pooling=true;
    depends_on:
      - postgres
    networks:
      - dev

  postgres:
    container_name: postgres-db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: AuthDb
    ports:
      - "5432:5432"
    networks:
      - dev
