version: '3.8'

networks:
  dev:
    driver: bridge
services:
  profile_service:
    container_name: profile-service
    image: profile
    build:
      context: .
      dockerfile: Services/Profile/Profile.Presentation/Dockerfile
    ports:
      - "5002:8080"
      - "5012:443"
    environment:
      - ASPNETCORE_HTTP_PORTS=5012
      - ASPNETCORE_HTTPS_PORTS=5002
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:443
      - ConnectionStrings__DefaultConnection=User ID =postgres;Password=postgres;Server=dockerPostgres;Port=5432;Database=ProfileDb;Pooling=true;
    depends_on:
      - postgres
    networks:
      - dev

  postgres:
    container_name: postgres-db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: AuthDb
    ports:
      - "5432:5432"
    networks:
      - dev
